title: This is "The Way"
email: kellycorwin@mail.weber.edu
description: >-
  Imagine walking into a room, people screaming, wearing strange clothes, hitting each other with sticks.
  Sound fun? Well it is, and after years of training and persistence I've become marginally good at it. Always room for improvement, but that's the point.

baseurl: "/my-first-website-Kelly-Corwin"
url: ""

# Chirpy theme settings
theme: jekyll-theme-chirpy
avatar: "/assets/images/Kelly_Corwin.jpeg"
tagline: "Kelly's Kendo Journey"

theme_mode: # leave blank for auto (light/dark based on user preference)

toc: true
paginate: 10

plugins:
  - jekyll-feed
