title: Why's Kelly Doing Kendo?
email: kellycorwin@mail.weber.edu
description: >- # this means to ignore newlines until "baseurl:"
  My first experience with Kendo was pretty typical. A room fool of people wearing weird clothes, shouting like maniacs, hitting each other with sticks. First impression is usually "What the hell am I even looking at?". 
  Over a decade later I am proudly one of those weirdos, and I'm happy to explain why we do what we don. 
logo: "/assets/images/Onikuma.jpg"
baseurl: "my-first-website-Kelly-Corwin" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme